// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApjsZ_rxH9OeC5DFjY0wsFa1ct7phPA3k',
    appId: '1:533892661765:web:d7104336c20ed88247526c',
    messagingSenderId: '533892661765',
    projectId: 'paccabelo',
    authDomain: 'paccabelo.firebaseapp.com',
    storageBucket: 'paccabelo.firebasestorage.app',
    measurementId: 'G-048XMLEP20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDysVX8tV1fzSe7b0g8ioW4eDcDqd6T7sE',
    appId: '1:533892661765:android:fbf613d92cc2e82847526c',
    messagingSenderId: '533892661765',
    projectId: 'paccabelo',
    storageBucket: 'paccabelo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApnm8QLYubDy3xk1SKBHFAzX4ddCnPDuI',
    appId: '1:533892661765:ios:8a9cf2424a4ba46047526c',
    messagingSenderId: '533892661765',
    projectId: 'paccabelo',
    storageBucket: 'paccabelo.firebasestorage.app',
    iosBundleId: 'com.example.pacCabelo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApnm8QLYubDy3xk1SKBHFAzX4ddCnPDuI',
    appId: '1:533892661765:ios:8a9cf2424a4ba46047526c',
    messagingSenderId: '533892661765',
    projectId: 'paccabelo',
    storageBucket: 'paccabelo.firebasestorage.app',
    iosBundleId: 'com.example.pacCabelo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApjsZ_rxH9OeC5DFjY0wsFa1ct7phPA3k',
    appId: '1:533892661765:web:26e82ef9d445aca747526c',
    messagingSenderId: '533892661765',
    projectId: 'paccabelo',
    authDomain: 'paccabelo.firebaseapp.com',
    storageBucket: 'paccabelo.firebasestorage.app',
    measurementId: 'G-02J3BVLF0W',
  );
}
